sudo: false
language: php
php:
#  - 5.2
#  - 5.3
#  - 5.4
#  - 5.5
  - 7.0
before_script:
  - pear channel-discover pear.horde.org
  - pear install -f channel://pear.horde.org/Horde_Test
  - ls -lR /home/travis/.phpenv/share/pear
  - pear install -f horde/horde_role
  - pear config-show
  - ls -lR /home/travis/.phpenv/share/pear
  
