sudo: false
language: php
php:
#  - 5.2
#  - 5.3
#  - 5.4
  - 5.5
  - 7.0
before_script:
  - pear channel-discover pear.horde.org
  - pear install -f -n channel://pear.horde.org/Horde_Test
  - pear install -f -n horde/horde_role
  - pear config-show
  - php -i | grep include_path
  - test -d /home/travis/.phpenv/versions/7.0.0/share/pear && ls -lR /home/travis/.phpenv/versions/7.0.0/share/pear
  - test -d /home/travis/.phpenv/versions/7.0.0/lib/php/pear && ls -lR /home/travis/.phpenv/versions/7.0.0/lib/php/pear
  - test -d /home/travis/.phpenv/versions/5.6.5/share/pear && ls -lR /home/travis/.phpenv/versions/5.6.5/share/pear
  - test -d /home/travis/.phpenv/versions/5.6.5/lib/php/pear && ls -lR /home/travis/.phpenv/versions/5.6.5/lib/php/pear
