sudo: false
language: php
php:
#  - 5.2
#  - 5.3
#  - 5.4
#  - 5.5
  - 7.0
before_script:
  - pear channel-discover pear.horde.org
  - pear install channel://pear.horde.org/Horde_Test
  - ls -lR /home/travis/.phpenv
