<?php

require __DIR__ . '/File.php';

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-02-19 at 15:43:35.
 */
class FileTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var File
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
      setlocale(LC_ALL, 'en_US.UTF-8');
      putenv('LC_ALL=en_US.UTF-8');
      putenv('LANG=en_US.UTF-8');
      putenv('LANGUAGE=C');
      $this->object = new File;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
      unset($this->object);
    }

    /**
     * @covers File::listFiles
     * @todo   Implement testListFiles().
     */
    public function testListFiles()
    {
      $this->assertEquals(array('高&执&行&力&的&打&造.txt'),
                          $this->object->listFiles());
    }

    public function testBaseName()
    {
      $files = $this->object->listFiles();
      $this->assertEquals('高&执&行&力&的&打&造.txt',
                          basename($files[0]));
    }
}
